### PR TITLE
Add more error handling: user input, case-insensitive Exe

### PR DESCRIPTION
**Pull request by idbrii**
Thanks for creating this great tool!

After not reading instructions well enough, I added some error handling to make it a bit friendlier.

I also added some handling around the Exe key in shortcuts. Looks like [UWPHook](https://github.com/BrianLima/UWPHook) (steamsync for Windows Store) uses 'exe' instead of 'Exe' which causes some false positive warnings.

If you want me to exclude some of the commits from this PR, let me know!

### CODE REVIEW

**Comment by jaydenmilne** [comment]
Thanks for the PR! Glad that someone is finding it useful, it is definitely rough around the edges. LGTM

**Comment by jaydenmilne** [comment]
Just noticed without your changes I'm having the same issue, but I'm on python 3.9 now. Wonder if that's it?

**Comment by jaydenmilne** [comment]
Shipped in 0.2.5

**Comment by idbrii** [comment]
> Just noticed without your changes I'm having the same issue, but I'm on python 3.9 now. 

You mean you're still getting this warning: 

> Warning: Entry in shortcuts.vdf has no `Exe` field! 

I'm on Python 3.9.1 and I'm not seeing it anymore.

BTW thanks for the quick merge! I installed on another PC and was delighted to see my steam path error message pop up. 😁

**Pull request merged**
